#!/bin/bash
set -e

. /etc/profile.d/rbenv.sh
BUNDLE=`which bundle`
GEM=`which gem`
. /opt/build-config

INSTALL_DIR=${INSTALL_DIR:-/home/app}
RUN_USER=${RUN_USER:-app}
LOG_DIR="/var/log/app"
KANDAN_CONF=/etc/supervisor/conf.d/kandan.conf
HUBOT_CONF=/etc/supervisor/conf.d/hubot.conf
HUBOT_VER=2.12.0

# add user
useradd -d ${INSTALL_DIR} -m ${RUN_USER}

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get -y install \
  supervisor \
  build-essential \
  curl \
  unzip \
  git-core \
  gcc \
  g++ \
  make

# node and dependencies
curl -sL https://deb.nodesource.com/setup | bash -
apt-get -y install nodejs \
  libpq5 sqlite3 libmysqlclient18 postgresql-client-common postgresql-client-9.3\
  libcurl3 libcurl3-nss libpcre3 libxml2 libxslt1.1 \
  libreadline5 libyaml-0-2\
  libmysqlclient-dev libsqlite3-dev libpq-dev \
  libcurl4-openssl-dev libpcre3-dev libxml2-dev libxslt-dev \
  libreadline-gplv2-dev libcxxtools-dev
# update npm
npm update -g npm
npm install -g coffee-script

###################################
# supervisord config

# move supervisord.log file to ${LOG_DIR}
sed 's|^logfile=.*|logfile='"${LOG_DIR}"'/supervisord.log ;|' -i /etc/supervisor/supervisord.conf

# populate ${LOG_DIR}
if [ ! -d ${LOG_DIR} ]; then
  mkdir -p -m 755 ${LOG_DIR}
fi

# populate ${KANDAN_CONF}
cat > ${KANDAN_CONF} <<__EOL__
[program:kandan]
command=${BUNDLE} exec thin start -e production
autostart=true
autorestart=false
username=${RUN_USER}
directory=${INSTALL_DIR}/kandan
stdout_logfile=${LOG_DIR}/%(program_name)s.log
stderr_logfile=${LOG_DIR}/%(program_name)s.log
environment=RBENV_ROOT=${RBENV_ROOT}
__EOL__

# populate ${HUBOT_CONF}
cat > ${HUBOT_CONF} <<__EOL__
[program:hubot]
command=${INSTALL_DIR}/hubot/bin/hubot -a kandan
autostart=true
autorestart=false
username=${RUN_USER}
directory=${INSTALL_DIR}/hubot
stdout_logfile=${LOG_DIR}/%(program_name)s.log
stderr_logfile=${LOG_DIR}/%(program_name)s.log
__EOL__

############################################
# Kandan
#
#  checkout kandan-i18n branch
sudo -u ${RUN_USER} -E -H git clone -b kandan-i18n --single-branch https://github.com/miurahr/kandan.git ${INSTALL_DIR}/kandan

${GEM} install execjs --no-document
${GEM} install mysql2 --no-document

# install gems into kandan/vendor/bundle
cd ${INSTALL_DIR}/kandan
sudo -u ${RUN_USER} -E -H ${BUNDLE} install --path vendor/bundle --without development,test

sed -ri 's/config.serve_static_assets = false/config.serve_static_assets = true/g' ${INSTALL_DIR}/kandan/config/environments/production.rb

chown -R ${RUN_USER}:${RUN_USER} ${INSTALL_DIR}

#############################################
# Hubot
#
# install
install -d -m 755 -o ${RUN_USER} -g ${RUN_USER} ${INSTALL_DIR}/hubot

# install source from github release
#curl -sL -o /tmp/hubot.zip https://github.com/github/hubot/archive/v${HUBOT_VER}.zip && sudo -u ${RUN_USER} -E -H unzip /tmp/hubot.zip -d ${INSTALL_DIR} && rm /tmp/hubot.zip
#cd ${INSTALL_DIR}/hubot-${HUBOT_VER}
#sudo -u ${RUN_USER} -E -H npm install
#sudo -u ${RUN_USER} -E -H mkdir -p hubot/bin
#sudo -u ${RUN_USER} -E -H make package

# install by yeoman and hubot generator
cd ${INSTALL_DIR}/hubot
npm install -g yo generator-hubot
sudo -u ${RUN_USER} -E -H yo hubot --defaults

# install kandan adapter and some
sudo -u ${RUN_USER} -E -H git clone https://github.com/miurahr/hubot-kandan.git node_modules/hubot-kandan
sudo -u ${RUN_USER} -E -H npm install faye
sudo -u ${RUN_USER} -E -H npm install ntwitter
sudo -u ${RUN_USER} -E -H git clone --depth 1 https://github.com/robhurring/hubot-redmine.git   node_modules/hubot-redmine
sudo -u ${RUN_USER} -E -H git clone --depth 1 https://github.com/hubot-scripts/hubot-trello.git node_modules/hubot-trello
sed -ri 's/"hubot-redis-brain": "0.0.2",/"hubot-redis-brain": "0.0.2","ntwitter": "*","hubot-kandan": "*","hubot-redmine": "*","hubot-trello": "*",/g'  ${INSTALL_DIR}/hubot/package.json
sed -ri 's/"hubot-redis-brain",/"hubot-redis-brain","hubot-redmine","hubot-trello"/g' ${INSTALL_DIR}/hubot/external-scripts.json

# supervisor cannot control status dependency. we insert sleep for waiting kandan become up
sed -ri 's/npm install/sleep 10 && npm install/g' ${INSTALL_DIR}/hubot/bin/hubot

# install all dependencies
sudo -u ${RUN_USER} -E -H npm install

##############################################
#
# cleanup dev files
#apt-get -y remove \
#  unzip gcc g++ make build-essential \
#  libmysqlclient-dev libsqlite3-dev libpq-dev \
#  libcurl4-openssl-dev libpcre3-dev libxml2-dev libxslt-dev \
#  libreadline-gplv2-dev

# clean apt caches and more
apt-get clean
apt-get -y autoremove
#find /var/lib/apt/lists/ -type f -exec rm -f {} \;

exit 0
