#!/bin/bash
set -e

. /etc/profile.d/rbenv.sh
BUNDLE=`which bundle`
GEM=`which gem`
. /opt/build-config

INSTALL_DIR=${INSTALL_DIR:-/home/app}
RUN_USER=${RUN_USER:-app}
LOG_DIR="/var/log/app"
KANDAN_CONF=/etc/supervisor/conf.d/kandan.conf
HUBOT_CONF=/etc/supervisor/conf.d/hubot.conf

# add user
useradd -d ${INSTALL_DIR} -m ${RUN_USER}

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get -y install \
  supervisor \
  build-essential \
  curl \
  unzip \
  git-core \
  gcc \
  g++ \
  make

# install dependency
curl -sL https://deb.nodesource.com/setup | bash -
apt-get -y install nodejs \
  libpq5 sqlite3 libmysqlclient18 postgresql-client-common postgresql-client-9.3\
  libcurl3 libcurl3-nss libpcre3 libxml2 libxslt1.1 \
  libreadline5 libyaml-0-2\
  libmysqlclient-dev libsqlite3-dev libpq-dev \
  libcurl4-openssl-dev libpcre3-dev libxml2-dev libxslt-dev \
  libreadline-gplv2-dev
npm update -g npm
# move supervisord.log file to ${LOG_DIR}
sed 's|^logfile=.*|logfile='"${LOG_DIR}"'/supervisord.log ;|' -i /etc/supervisor/supervisord.conf

# populate ${LOG_DIR}
if [ ! -d ${LOG_DIR} ]; then
  mkdir -p -m 755 ${LOG_DIR}
fi

# populate ${KANDAN_CONF}
cat > ${KANDAN_CONF} <<__EOL__
[program:kandan]
command=${BUNDLE} exec thin start -e production
autostart=true
autorestart=false
username=${RUN_USER}
directory=${INSTALL_DIR}/kandan
stdout_logfile=${LOG_DIR}/%(program_name)s.log
stderr_logfile=${LOG_DIR}/%(program_name)s.log
environment=RBENV_ROOT=${RBENV_ROOT}
__EOL__

# populate ${HUBOT_CONF}
cat > ${HUBOT_CONF} <<__EOL__
[program:hubot]
command=${INSTALL_DIR}/hubot/bin/hubot -a kandan
autostart=true
autorestart=false
username=${RUN_USER}
directory=${INSTALL_DIR}/hubot
stdout_logfile=${LOG_DIR}/%(program_name)s.log
stderr_logfile=${LOG_DIR}/%(program_name)s.log
__EOL__

# install yeoman and hubot generator
npm install -g yo generator-hubot

# install
cd ${INSTALL_DIR}
sudo -u ${RUN_USER} -E -H git clone https://github.com/miurahr/kandan.git
cd kandan
sudo -u ${RUN_USER} -E -H git checkout i18n

${GEM} install execjs
${GEM} install mysql2

# install gems into kandan/vendor/bundle
sudo -u ${RUN_USER} -E -H ${BUNDLE} install --path vendor/bundle --without development,test

sed -ri 's/config.serve_static_assets = false/config.serve_static_assets = true/g' ${INSTALL_DIR}/kandan/config/environments/production.rb

chown -R ${RUN_USER}:${RUN_USER} ${INSTALL_DIR}

# install hubot
install -d -m 755 -o ${RUN_USER} -g ${RUN_USER} ${INSTALL_DIR}/hubot
cd ${INSTALL_DIR}/hubot
sudo -u ${RUN_USER} -E -H yo hubot --defaults

# install kandan adapter and some
sudo -u ${RUN_USER} -E -H git clone https://github.com/miurahr/hubot-kandan.git       node_modules/hubot-kandan
sudo -u ${RUN_USER} -E -H git clone https://github.com/robhurring/hubot-redmine.git   node_modules/hubot-redmine
sudo -u ${RUN_USER} -E -H git clone https://github.com/hubot-scripts/hubot-trello.git node_modules/hubot-trello

sed -ri 's/"hubot-redis-brain": "0.0.2",/"hubot-kandan": "*","hubot-redmine": "*","hubot-trello": "*",/g'  ${INSTALL_DIR}/hubot/package.json
sed -ri 's/"hubot-redis-brain",//g' ${INSTALL_DIR}/hubot/external-scripts.json
sudo -u ${RUN_USER} -E -H npm install

# cleanup dev files
apt-get -y remove \
  libmysqlclient-dev libsqlite3-dev libpq-dev \
  libcurl4-openssl-dev libpcre3-dev libxml2-dev libxslt-dev \
  libreadline-gplv2-dev

# clean apt caches, build dependency
apt-get clean
apt-get -y autoremove
find /var/lib/apt/lists/ -type f -exec rm -f {} \;
